install: 
	cp ./asterisk-router.conf /etc/NetSDS/
	chown _asterisk:pbxadmin /etc/NetSDS/asterisk-router.conf 
	cp ./NetSDS-route.pl /usr/lib/asterisk/agi-bin/ 
	chown _asterisk:pbxadmin /usr/lib/asterisk/agi-bin/NetSDS-route.pl
	cp ./NetSDS-AGI-integration.pl /usr/lib/asterisk/agi-bin/
	chown _asterisk:pbxadmin /usr/lib/asterisk/agi-bin/NetSDS-AGI-integration.pl

